# netlify.toml

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[headers]]
  for = "/*.js"
    [headers.values]
      Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
      Content-Type = "text/css"

# Uncomment the following section if you need to configure redirects for a Single Page Application
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

# Optional settings for Netlify Dev
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

# For more information on configuring this file, see: https://ntl.fyi/file-based-build-config
